version: "3.8"
services:
  php:
    container_name: php_cont
    build: ./docker/php/
    networks:
      - backend
    volumes:
      - ./public/:/var/www/html/
      - ./logs/php/:/usr/local/etc/logs/
  apache:
    container_name: apache_cont
    build: ./docker/apache/
    depends_on:
      - php
    networks:
      - frontend
      - backend
    ports:
      - "80:80"
    volumes:
      - ./public/:/var/www/html/
      - ./logs/apache/:/usr/local/apache2/logs/
networks:
  frontend:
  backend:
